# Usa una imagen base de Node
FROM node:22-alpine

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia solo los archivos de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el esquema de Prisma para generar el cliente
COPY prisma ./prisma/

# Genera el cliente de Prisma
RUN npx prisma generate

COPY . .

EXPOSE 3000

# El comando para iniciar la app en modo desarrollo
CMD ["npm", "run", "start:dev"]